### PR TITLE
hope this works

### PR DESCRIPTION
**Pull request by norman-promise-neverland**
hoping that this works

### CODE REVIEW

**Review by rizel-botany — COMMENTED** [review]
not great @norman-promise-neverland

**Comment by rizel-botany** [comment]
will you see this comment @norman-promise-neverland

**Comment by rizel-botany** [comment]
i think i am trying to do something @norman-promise-neverland

**Comment by rizel-botany** [comment]
@norman-promise-neverland you here?

**Comment by rizel-botany** [comment]
i dont care @norman-promise-neverland

**Comment by rizel-botany** [comment]
@holiday inn

**Comment by rizel-botany** [comment]
rizel does this @norman-promise-neverland

**Comment by rizel-botany** [comment]
how are you? @norman-promise-neverland

**Comment by rizel-botany** [comment]
read a book @norman-promise-neverland

**Comment by rizel-botany** [comment]
yo gi oh @norman-promise-neverland

**Comment by rizel-botany** [comment]
no way! @norman-promise-neverland

**Comment by rizel-botany** [comment]
you give me a heart attack @norman-promise-neverland

**Comment by rizel-botany** [comment]
hiiii @norman-promise-neverland

**Comment by rizel-botany** [comment]
why dont u work @norman-promise-neverland

**Comment by rizel-botany** [comment]
all this that you have changed @norman-promise-neverland

**Comment by rizel-botany** [comment]
you can still be an engineer one day @norman-promise-neverland

**Comment by rizel-botany** [comment]
coding is like a puzzle @norman-promise-neverland

**Comment by rizel-botany** [comment]
@norman-promise-neverland why dont you work

**Comment by rizel-botany** [comment]
ready @norman-promise-neverland

**Comment by norman-promise-neverland** [comment]
@rizel-botany cardi

**Comment by norman-promise-neverland** [comment]
now this is annoying @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany please be here

**Comment by norman-promise-neverland** [comment]
listening to rain @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany closer to the goal

**Comment by norman-promise-neverland** [comment]
check for red error @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany the red error is the answer

**Comment by norman-promise-neverland** [comment]
feel the wind @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany sigh

**Comment by norman-promise-neverland** [comment]
landscape @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany doubles

**Comment by norman-promise-neverland** [comment]
hurting @rizel-botany

**Comment by norman-promise-neverland** [comment]
Wendy williams @rizel-botany

**Comment by rizel-botany** [comment]
I want to try @norman-promise-neverland

**Comment by norman-promise-neverland** [comment]
mlk jr @rizel-botany

**Comment by norman-promise-neverland** [comment]
this is so annoying @rizel-botany 617

**Comment by norman-promise-neverland** [comment]
are you going to choose violence 617 @rizel-botany yes i am

**Comment by norman-promise-neverland** [comment]
who are you 617 @rizel-botany sad

**Comment by norman-promise-neverland** [comment]
add a new one @rizel-botany

**Comment by rizel-botany** [comment]
i want to find this @rizel-botany

**Comment by rizel-botany** [comment]
i want to find this @norman-promise-neverland

**Comment by rizel-botany** [comment]
@norman-promise-neverland what a time

**Comment by rizel-botany** [comment]
@norman-promise-neverland my mouths on fire.

**Comment by rizel-botany** [comment]
health insurance @norman-promise-neverland

**Comment by rizel-botany** [comment]
@norman-promise-neverland super bowl

**Comment by norman-promise-neverland** [comment]
@amongus-02/wesmart do you all see this?

**Comment by norman-promise-neverland** [comment]
hey @amongus-02/wesmart do you all see this?

**Comment by norman-promise-neverland** [comment]
hey @rizel-botany

**Comment by norman-promise-neverland** [comment]
I want this to work @rizel-botany

**Comment by norman-promise-neverland** [comment]
does this work @amongus-02/wesmart

**Comment by rizel-botany** [comment]
I went to high school @norman-promise-neverland

**Comment by norman-promise-neverland** [comment]
don't break the current way that it works @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany yep this works!

**Comment by rizel-botany** [comment]
are you not embarrassed @norman-promise-neverland

**Comment by rizel-botany** [comment]
@norman-promise-neverland i am embarrassed for you

**Comment by rizel-botany** [comment]
@norman-promise-neverland you are a tourist

**Comment by rizel-botany** [comment]
@norman-promise-neverland

**Comment by rizel-botany** [comment]
i am tired @norman-promise-neverland

**Comment by rizel-botany** [comment]
@amongus-02/wesmart

**Comment by rizel-botany** [comment]
does this match @amongus-02/wesmart

**Comment by norman-promise-neverland** [comment]
@rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany hello

**Comment by norman-promise-neverland** [comment]
Hello @rizel-botany

**Comment by norman-promise-neverland** [comment]
www.cube.dev/docs/@cube-js/fdasflkj

**Comment by norman-promise-neverland** [comment]
@amongus-wesmart

**Comment by rizel-botany** [comment]
@amongus-02/wesmart

**Comment by rizel-botany** [comment]
why are you not working @norman-promise-neverland

**Comment by rizel-botany** [comment]
I wonder why this doesn't work @amongus-02/wesmart

**Comment by rizel-botany** [comment]
hello @amongus-02/wesmart

**Comment by rizel-botany** [comment]
@norman-promise-neverland

**Comment by norman-promise-neverland** [comment]
does this work @amongus-02/wesmart

**Comment by norman-promise-neverland** [comment]
who are you @amongus-02/wesmart

**Comment by norman-promise-neverland** [comment]
@amongus-02/wesmart

**Comment by norman-promise-neverland** [comment]
@amongus-02/wesmart HELLLO 👍

**Comment by norman-promise-neverland** [comment]
www.cube.dev/docs/@cube-js/fdasflkj

**Comment by norman-promise-neverland** [comment]
one more thing @amongus-02/wesmart don't leave

**Comment by norman-promise-neverland** [comment]
one more thing @rizel-botany don't leave

**Comment by norman-promise-neverland** [comment]
This is an example of a user mention after wards @rizel-botany

**Comment by norman-promise-neverland** [comment]
@rizel-botany an example of a user mention before

**Comment by norman-promise-neverland** [comment]
@rizel-botany

**Comment by norman-promise-neverland** [comment]
An example of @rizel-botany a mention in between

**Comment by norman-promise-neverland** [comment]
An example of a team mention after @amongus-02/wesmart

**Comment by norman-promise-neverland** [comment]
@among-us02/wesmart team mention before

**Comment by norman-promise-neverland** [comment]
@among-us02/wesmart

**Comment by norman-promise-neverland** [comment]
in @amongus-02/wesmart between

**Comment by norman-promise-neverland** [comment]
@amongus-02/wesmart do you work

**Comment by norman-promise-neverland** [comment]
@amongus-02/wesmart

**Comment by rizel-botany** [comment]
www.cube.dev/docs/@cube-js/fdasflkj

**Comment by rizel-botany** [comment]
that didnt mention anyone but this will www.cube.dev/docs/@cube-js/fdasflkj 
 @norman-promise-neverland

**Review by rizel-botany — APPROVED** [review]
great job!

**Comment by norman-promise-neverland** [comment]
last comment @rizel-botany

**Comment by norman-promise-neverland** [comment]
https://cube.dev/docs/@cubejs-client-core#result-set-raw-data

**Pull request merged**
